### ISSUE TITLE
Possibility to jail on a few packages

### ISSUE THREAD

**Issue by LEVI-RIVKIN** [rollup/rollup-plugin-node-resolve#116]
I need to resolve a few specific node modules packages.

```
resolve({
    jail: ['path', 'path']
})
```

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
