### ISSUE TITLE
Conflict when importing duplicated version conflicted modules (latest npm)

### ISSUE THREAD

**Issue by AlbertoElias** [rollup/rollup-plugin-node-resolve#118]
Now npm tries to install a flat dependency tree, but when there's a version conflict, it installs a the conflicted module in a sub `node_modules` directory.

So if module *a* depends on *c#v1* and *b* depends on *c#v2*, *c#v1* will be installed in the root level `node_modules` directory, whil *c#v2* will be install in `node_modules/b/node_modules`.

This seems to produce a conflict when compiling using this plugin, and the conflicted module is `undefined` in the bundle. I've had this issue compiling https://github.com/mafintosh/webrtc-swarm and https://github.com/mafintosh/signalhub which use different versions of `through2`

**Comment by mecurc** [comment]
Those packages have no updates > 2 years. When I try to build project with it I got thousands of circular dependencies warnings. Best way to resolve this: mark them as external.

I think it can be closed too.

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
