### ISSUE TITLE
Bundle Promise polyfill

### ISSUE THREAD

**Issue by ericf** [rollup/rollup-plugin-node-resolve#18]
Without a `Promise` polyfill, this plugin can't be use in Node 0.10. This package currently does `new Promise()` without loading a polyfill when needed.

**Comment by eventualbuddha** [comment]
Not to be dismissive, but is there a compelling reason to support Node 0.10?

**Comment by ericf** [comment]
rollup/rollup includes a Promise polyfill and tests Node 0.10, I figured the official plugins would as well. Right now I'm loading the `es6-promise` polyfill in my `rollup.config.js`, but that feels clunky and brittle. 

I ran into this in a project which I'm testing in Node 0.10, 0.12, 4, and 5 in Travis.

**Comment by TrySound** [comment]
@ericf Using node 0.10 feels clunky and brittle.

**Comment by ericf** [comment]
@TrySound I have to support apps that run in Node 0.10, so my libs have to run and be tested in Node 0.10, which is how I hit this…

I honestly thought this was an oversight since the main Rollup package includes a Promise polyfill (when needed).

**Comment by TrySound** [comment]
I think the better solution is removing polyfill from rollup at all. node 0.10 is like IE6. We should let to use it only with polyfills.

**Comment by ericf** [comment]
I'm happy to write the PR to make this package work in Node 0.10. See: https://github.com/rollup/rollup/issues/189

**Comment by ericf** [comment]
How would you recommend loading polyfills for the CLI? A `--require` option like `mocha` or something?

**Comment by TrySound** [comment]
I suggest do not use cli with polyfills. Simple `.js` file is not much bigger than rollup.config.js

**Comment by Rich-Harris** [comment]
I suppose this issue is bigger than this one plugin – we need to decide what our stance on this is across *all* plugins. Given that we require plugin functions to return promises, it makes sense for there to be some 'official' guidance, much as it would be easier to just deal with this specific issue. I see three options:

1. We don't support 0.10 (and should therefore remove the polyfill from Rollup itself)
2. We expect plugin authors to bring their own polyfill (possibly via rollup-pluginutils?)
3. We allow plugin functions to use a node style callback (i.e. if it returns a promise, use that, if not, wait for it to call the callback)

Option 3 is the most flexible, albeit a bit messy. Option 2 is definitely less than ideal – some plugin authors will undoubtedly choose not to support 0.10, and that would be a reasonable decision on their part.

I'm kind of leaning towards option 1. I think it's reasonable to expect certain applications and libraries to work on 0.10, but Rollup is only ever used as a devDependency – it's never needed at runtime, only at build time. The issue is that we're conflating the target environment with the development environment – no-one is *developing* on 0.10. 

@ericf One possible solution:

```bash
nvm use stable
npm run build
nvm use 0.10
npm test
```

Is that a practical solution?

**Comment by eventualbuddha** [comment]
I prefer options 1 and 3, in that order.

**Comment by ericf** [comment]
I just ended up removing my `rollup.config.js` files and instead stuck with creating a `build-dist.js` script and using the Rollup API directly.

The reason I mentioned the `--require` option is that it would allow polyfilling the runtime, and the CLI could load in the `--require`-d module before the plugin modules.

One issue I've found with Rollup's current `getBundle()` method is that it always returns a non built-in Promise instance. Because of this, I end up casting it to a built-in Promise `Promise.resolve()`, so I can use node's `unhandledRejection` event to exit a script on error:
```js
process.on('unhandledRejection', (reason) => {throw reason;});
```

Option 2 has to be a given when people are using ECMAScript features beyond the baseline v8 version that rollup will work with. If my plugin is using a new ECMAScript API, say `Array.prototype.includes`, I'll have to use a polyfill in my plugin.

> Is that a practical solution?

This would be something one would need to figure out how to do in a test environment like Travis CI.

**Comment by TrySound** [comment]
I'm only for option 1.

**Comment by Victorystick** [comment]
I'm also for Option 1.

@ericf Couldn't you just have added a `require` call in `rollup.config.js` to include a Promise polyfill?

**Comment by ericf** [comment]
@Victorystick yeah, probably. But going with Option 1 will likely not allow that to work since Rollup might create a promise before invoking the config file.

**Comment by piuccio** [comment]
Just encountered this issue.

I use [AWS lambda](https://aws.amazon.com/lambda/) which is a wonderful system that unfortunately runs on [node 0.10](http://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html).

I bundle with rollup on travis and run my unit tests against the bundled version. For sanity I prefer running tests on node 0.10, because that's where my code will run, but becuase of this issue either I can't use rollup or I have to run my tests in a different environment reducing my confidence.

**Comment by TrySound** [comment]
@piuccio You can include polyfill in custom js and run rollup from it. Yeah, without cli (`node rollup.config.js` in this case). But you will get what you want.
