### ISSUE TITLE
Feature request: error if there are still imports

### ISSUE THREAD

**Issue by appsforartists** [rollup/rollup-plugin-node-resolve#188]
Here is my current configuration:

```javascript
    resolve({
      modulesOnly: true,

      // Whitelist imports to assert that we only inline things that we've
      // injected the licenses for.
      only: [
        'indefinite-observable',
        'wobble',
        'symbol-observable',
        'fast-equals',
       ],
    }),
```

I'm interested in adding a check that will throw if there are still `import` statements in the resulting bundle (e.g. `exhaustive: true`).  The purpose of such a check would be to require a manual intervention before adding any dependencies to a published bundle: in this case, to ensure that the correct licenses have also been included.

Would you be amenable to a patch to support this, or should I make a separate plugin?

**Comment by LarsDenBakker** [comment]
+1 would really like to have this as well

**Comment by mecurc** [comment]
Any updates? Is still need this feature?

(`skip` was dropped it previous releases)

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
