### ISSUE TITLE
native modules .node problem

### ISSUE THREAD

**Issue by DanielMazurkiewicz** [rollup/rollup-plugin-node-resolve#234]
- Node-Resolve Plugin Version: 5.2.0
- Rollup Version: 1.16.4
- Operating System (or Browser): Linux
- Node Version: 11.0

### How Do We Reproduce?

yarn add atomic-counters
```
console.log(require('atomic-counters'));
```

### Expected Behavior
```
const ac = require('./nameAsHashOfFileOrSomethingLikeThat.node');
// file .node in same directory as js file
```

### Actual Behavior
```
const ac = require('../../build/Release/atomicCounters.node');
// that path is wrong, points to nothing
```

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
