### ISSUE TITLE
Resolve breaks certain css files

### ISSUE THREAD

**Issue by dkumor** [rollup/rollup-plugin-node-resolve#237]
This looks like an issue with the interaction of resolve and postcss. Certain imported css files are included without an issue, but others disappear without a trace. Note that this happens *only* when using resolve (see details), so I have submitted it here. I hope that this is the right place for it!

The issue appears when trying to import vuetify's css with resolve and postcss.

- Node-Resolve Plugin Version: `5.2.0`
- Rollup Version: `1.20.2`
- Operating System (or Browser): `archlinux`
- Node Version: `12.9.1`

### How Do We Reproduce?

When trying to import vuetify css with resolve, it simply is not included, as if the import didn't exist
```js
// test.js
import 'vuetify/dist/vuetify.css';
```

```bash
npm i rollup rollup-plugin-node-resolve rollup-plugin-postcss vuetify codemirror
```

```js
// rollup.config.js
import resolve from "rollup-plugin-node-resolve"
import postcss from "rollup-plugin-postcss"

export default {
  input: "test.js",
  output: {
    file: "test.mjs",
    format: "es"
  },
  plugins: [resolve(),postcss()]
}
```

Running rollup with `rollup -c`

### Expected Behavior

Importing certain files with resolve works fine
```js
// test.js
import 'codemirror/lib/codemirror.css';
```

Importing the problematic file directly (without resolve) also works without issue
```bash
cp node_modules/vuetify/dist/vuetify.css ./vuetify.css
```
```js
// test.js
import "./vuetify.css"
```

Trying to import a file that does not exist gives the expected error
```js
import "doesnotexist.css"; // as expected, fails with "Unresolved dependencies" error
```

### Actual Behavior

```js
// test.js
import 'vuetify/dist/vuetify.css';
```
An empty bundle is generated, without any error.

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:

**Comment by hiendv** [comment]
@shellscape The bug remains when setting up the project with lerna.
