### ISSUE TITLE
dedupe & yarn workspaces/lerna

### ISSUE THREAD

**Issue by btakita** [rollup/rollup-plugin-node-resolve#238]
- Node-Resolve Plugin Version: 5.2.0
- Rollup Version: 1.23.1
- Operating System (or Browser): Arch Linux
- Node Version: 12.11.1

### How Do We Reproduce?

```shell
npx degit ctx-core/lerna-template myproject
cd myproject
npx degit ctx-core/sapper-template#rollup-plugin-node-resolve-issues-238 packages/web
yarn
bin/tsc-build.sh
cd packages/web
yarn run dev
```

### Expected Behavior

Npm packages installed using yarn workspaces should be included in build when using dedupe.

### Actual Behavior

`could not be resolved – treating it as an external dependency` warnings

**Comment by btakita** [comment]
It looks like the `importee` does not allow yarn workspaces to resolve the location of the package.

https://github.com/rollup/rollup-plugin-node-resolve/blob/master/src/index.js#L224

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
