### ISSUE TITLE
There are no output files when using resolve

### ISSUE THREAD

**Issue by stwic** [rollup/rollup-plugin-node-resolve#243]
- Node-Resolve Plugin Version: 5.2.0
- Rollup Version: 1.26.5
- Operating System (or Browser): Windows 10 / Google Chrome Version 78.0.3904.97
- Node Version: v10.16.0

### How Do We Reproduce?
https://github.com/stwic/rollup-node-resolve-test

### Expected Behavior
Create dist folder with three different files .esm.js, .min.js, .umd.js
Cmd should say created ./dist/file.extension

### Actual Behavior

cmd logs ./src/main.vue -> dist/file.extension 
and starts next build where it logs the same thing
On completion, there is no dist folder and no files.

##### Expected Behavior after we comment out the resolve()
Create dist folder with three different files .esm.js, .min.js, .umd.js
Cmd should say created ./dist/file.extension
##### Actual Behavior after we comment out the resolve()
Works as expected

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
