### ISSUE TITLE
Browser resolve fails in Node 6: opts.filename is undefined

### ISSUE THREAD

**Issue by nolanlawson** [rollup/rollup-plugin-node-resolve#38]
This error is thrown only on Node 6, only when using `rollup-plugin-node-resolve`, and only when using `browser: true`. Those three conditions need to be met in order to reproduce this bug.

The offending line of of code is [in node-browser-resolve](https://github.com/defunctzombie/node-browser-resolve/blob/a238dd1ca8db9319cdd6b6340358a09f298c9156/index.js#L218) (`opts.filename` is undefined), so it's possible this bug doesn't exist here but rather in that repo. I wasn't sure, so I'm filing it here.

I have [a gist to reproduce](https://gist.github.com/nolanlawson/193486eb1d4046701c464324fe67511c).

Steps:

```bash
git clone https://gist.github.com/e029b935459d4cdb5097d1a74485be63.git gist && cd gist
npm i && node build.js
```

The error received is:

```
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at resolve (/Users/nolan/Desktop/repro-rollup-bug/node_modules/browser-resolve/index.js:218:21)
...
```

**Comment by nkoterba** [comment]
👍  This is a critical issue we are facing as well.

In short, I believe that Node 6's internal `path` object no longer allows undefined inputs.  Previously, I think this "bug" was overlooked by many `browser-resolve` users because failing to pass in a `filename` to browser-resolve's configuration block just silently failed and Node v5.x just happily carried on.

In short, I think this can be handled multiple ways:

1) I think `node-browser-resolve` should be updated to provide a default value if `filename` is not passed in to the configuration block of `browser-node-resolve`. There is already an outstanding pull request here: https://github.com/defunctzombie/node-browser-resolve/pull/80 and I just made another one: https://github.com/defunctzombie/node-browser-resolve/pull/81

2) Since the maintainer(s) of `browser-node-resolve` have not yet fixed this issue, also fix the `rollup-plugin-node-resolve`.  I have submitted a pull request for this change: https://github.com/rollup/rollup-plugin-node-resolve/pull/40

**Comment by tivac** [comment]
https://github.com/defunctzombie/node-browser-resolve/pull/80 was just merged, and is now available on npm as `browser-resolve@1.11.2`, which should match the current `package.json` value for `browser-resolve` ([here](https://github.com/rollup/rollup-plugin-node-resolve/blob/master/package.json#L32)) so this should be good!

**Comment by FredyC** [comment]
I confirm that issue is indeed resolved by updating said module.

**Comment by Rich-Harris** [comment]
Sorry, just seeing this now – am I right in thinking this and #40 can be closed if the issue has been fixed upstream? thanks

**Comment by tivac** [comment]
@Rich-Harris Yes, fixed upstream. `npm update` should be all anyone needs.

**Comment by PixelVibe** [comment]
Hello, I am still having the same problem after the update. Do I have to manually update the dependency of browser-resolve in the package.json of the module?

**Comment by Mevrael** [comment]
@PixelVibe I've deleted node_modules folder and clean `npm install` worked for me.

**Comment by lammas** [comment]
@PixelVibe I'm also experiencing the same issue. Deleting `node_modules` and doing a clean `npm install` did not help.
