### ISSUE TITLE
Support for custom `node_modules` search paths

### ISSUE THREAD

**Issue by zaygraveyard** [rollup/rollup-plugin-node-resolve#75]
Can you add support for using custom `node_modules` search paths?

Solution can be one of:
* Add support for [`NODE_PATH` environment variable](https://nodejs.org/api/cli.html#cli_node_path_path)
* Add support for specifying custom `paths` option (like `browser-resolve`'s `paths`)
* Add support for specifying a custom `resolveId` function
* Add support for specifying custom `resolveId` options

I'm willing to submit a PR if needed

Thanks

**Comment by Rich-Harris** [comment]
You can now specify `customResolveOptions` which are passed through directly to `node-resolve`, does that fix your issue?

**Comment by zaygraveyard** [comment]
Yes it does, thank you :+1: 

Although it would nice if using the `NODE_PATH` environment variable is the default.
Any chance this could be implemented?
Thanks

**Comment by Rich-Harris** [comment]
I feel like that's more the responsibility of [node-resolve](https://github.com/substack/node-resolve) itself — I'm reluctant to add a lot of logic that extends this plugin beyond what node-resolve offers, because we'll end up out of sync. Maybe open an issue/PR there?

Alternatively, you should be able to add that functionality with `customResolveOptions` fairly easily:

```js
plugins: [
  resolve({
    customResolveOptions: {
      paths: process.env.NODE_PATH.split( /[;:]/ )
    }
  })
]
```
