### ISSUE TITLE
What if the package under node_modules has name ending in .js

### ISSUE THREAD

**Issue by charandas** [rollup/rollup-plugin-node-resolve#84]
I am running into an issue with [Mapbox.js](https://github.com/mapbox/mapbox.js#usage-with-browserify).

On `import 'mapbox.js'`: throws this error, which unfortunately does not say much:

```
Error: Unexpected token
    at error (/home/cbatra/myproject/node_modules/rollup/dist/rollup.js:170:12)
    at Module.error$1 [as error] (/home/cbatra/myproject/node_modules/rollup/dist/rollup.js:7997:2)
    at tryParse (/home/cbatra/myproject/node_modules/rollup/dist/rollup.js:7700:10)
    at new Module (/home/cbatra/myproject/node_modules/rollup/dist/rollup.js:7735:14)
    at /home/cbatra/myproject/node_modules/rollup/dist/rollup.js:9481:17

```

**Comment by azinasili** [comment]
I'm not 100% sure yet, but I believe I'm running into the same issue with [lory.js](https://meandmax.github.io/lory/).

**Comment by porsager** [comment]
I don't think there's an issue with modules ending in `.js` I have no problem using eg. `chart.js`.

The issue you're seeing with the `mapbox.js` module is because it does a require of it's own package.json inside it's code. If you're not using `rollup-plugin-json` you will get this error.

Try to add `rollup-plugin-json` to your plugins and it should work ;)

**Comment by charandas** [comment]
Good to know. Thanks @porsager.
